### ISSUE TITLE
Error with old version of flutter_colorpicker

### ISSUE THREAD

**Issue by wahidanvary** [codegrue/flutter_material_pickers#40] opened 2021-09-25 18:10 UTC
When I use color picker on my app in the new version of dart I got the error:
```
Because flutter_material_pickers 3.1.0 depends on flutter_colorpicker ^0.4.0 and no versions of flutter_material_pickers match >3.1.0 <4.0.0, flutter_material_pickers ^3.1.0 requires flutter_colorpicker ^0.4.0.
And because every version of card_settings from path depends on flutter_material_pickers ^3.1.0, every version of card_settings from path requires flutter_colorpicker ^0.4.0.
So, because "ebarge" depends on both flutter_colorpicker ^0.6.0 and card_settings from path, version solving failed.
pub get failed (1; So, because "ebarge" depends on both flutter_colorpicker ^0.6.0 and card_settings from path, version solving failed.)
```

environment:
  sdk: ">=2.13.4 <3.0.0"

**Comment by bobatsar** [comment] 2021-09-27 08:59
Duplicate of https://github.com/codegrue/flutter_material_pickers/issues/36 
We have to wait until an updated version will be published or use my workaround or use the master branch of this packege as described here
https://github.com/codegrue/flutter_material_pickers/pull/37

**Comment by codegrue** [comment] 2021-09-29 02:58
3.1.2 deployed which should fix this issue

**Closed by codegrue** 2021-09-29 02:58 UTC
